version: "3.7"

services:
  redis-store:
    image: redis:alpine
    ports: ["6379"]
    networks:
      api-internal:

  api:
    image: dockersamples/product-api:1
    build:
      context: .
    ports:
      - "8080:5000"
      - "3000:3000"
      - "54739:54739"
    volumes:
      - .:/home/api
    networks:
      api-external:
      api-internal:

networks:
  api-external:
  api-internal: